### ISSUE TITLE
Version for 1.7.0

### ISSUE THREAD

**Issue by thery** [math-comp/multinomials#16]
This does not compile anymore in 1.7.0
The files : bigenoug, finmap and order have disappeared

**Comment by strub** [comment]
Huh ? I should depend on the finmap package. I’m going to check that. The
fix should be simple.

Le mer. 2 mai 2018 à 15:33, Laurent Théry <notifications@github.com> a
écrit :

**Comment by CohenCyril** [comment]
fixed by #18
