### ISSUE TITLE
Misnomer?

### ISSUE THREAD

**Issue by amahboubi** [math-comp/multinomials#22]
Isn't the name of this library misleading?

**Comment by strub** [comment]
The name of this library is historical :) I am open to suggestions.

**Comment by CohenCyril** [comment]
`mpoly`, `multivariate`, `multivariate-polynomials`, `monalg`, `monomial-algebras`?

**Comment by thery** [comment]
I thought ultimately it should be merged into algebra?

**Comment by strub** [comment]
Well, it seems that I've a dependence on real-closed.

**Comment by amahboubi** [comment]
More precisely on `big_enough`. I agree with @thery that it should be merged. Either by refactoring the proofs or by integrating a `big_enough`-like library as well.

**Comment by amahboubi** [comment]
> `mpoly`, `multivariate`, `multivariate-polynomials`, `monalg`, `monomial-algebras`?

I do not like `multivariate`, it's too generic. With the actual content of the libraries, `monomial-algebras` might also be either misleading or a bit conceited. I prefer `mpoly`, `mpolynomial` or may be even `polynomials`. Although these names are not fair to `freeg`.

**Comment by strub** [comment]
> More precisely on `big_enough`. I agree with @thery that it should be merged. Either by refactoring the proofs or by integrating a `big_enough`-like library as well.

I think big-enough now has its dedicated package. I should change the opam meta-information.

**Comment by strub** [comment]
> > `mpoly`, `multivariate`, `multivariate-polynomials`, `monalg`, `monomial-algebras`?
> 
> I do not like `multivariate`, it's too generic. With the actual content of the libraries, `monomial-algebras` might also be either misleading or a bit conceited. I prefer `mpoly`, `mpolynomial` or may be even `polynomials`. Although these names are not fair to `freeg`.

I am in favour of mpolynomials.
