### ISSUE TITLE
Dependencies for Coq 8.10 + Mathcomp 1.9

### ISSUE THREAD

**Issue by amahboubi** [math-comp/multinomials#29]
Which version of `finmap` should I use to compile this library? Eventually, I would like to compile CoqEAL. See [here](https://github.com/CoqEAL/CoqEAL/issues/23).

For now, using version 1.3.4 of `finmap` I get:

```
File "./refinements/multipoly.v", line 651, characters 31-37:
Error:
In environment
n : nat
m1 : 'X_{1.. n}
m1' : seqmultinom
rm1 : refines Rseqmultinom m1 m1'
m2 : 'X_{1.. n}
m2' : seqmultinom
rm2 : refines Rseqmultinom m2 m2'
E : m1 == m2
E' : mnmc_eq_seq m1' m2'
Unable to unify "?M3449 = false" with
 "mnmc_lt_seq m1' m2' =
  order.Order.POrderDef.lt (mdeg m1 :: m1) (mdeg m2 :: m2)".

Makefile.coq:658: recipe for target 'refinements/multipoly.vo' failed
```

**Comment by strub** [comment]
I am going to check. I don't think that I ever tried with Coq 8.10.

**Comment by amahboubi** [comment]
@strub, thanks! More precisely, I am testing with coq 8.10.1.

**Comment by amahboubi** [comment]
Issue solved : `multinomials` complies with `finmap` 1.2.

**Comment by strub** [comment]
Reopening. I do remember having updated multinomials to complies with finmap 1.3. And the opam files indicates: `"coq-mathcomp-finmap"    {>= "1.3.4" & < "1.4~"}`.

**Comment by CohenCyril** [comment]
The explanation is that there was no release subsequent to PR #28

**Comment by CohenCyril** [comment]
It's just been waiting to happen since June 28 and noone realized/did it.

**Comment by amahboubi** [comment]
And that this PR had a misleading title and no description.

**Comment by strub** [comment]
I just released a version 1.4 based on PR #30 (after having fixed the CI...) What is the process s.t. it goes to opam?

**Comment by strub** [comment]
coq/opam-coq-archive#1034

**Comment by strub** [comment]
@amahboubi could you confirm that you are now able to compile multinomials v1.4?

**Comment by hivert** [comment]
The version on opam still mention
```
"coq-mathcomp-finmap"    {>= "1.3.4" & < "1.4~"}
```
So that it doesn't work with `finmap 1.4`

**Comment by strub** [comment]
Arf, you're right. I made a PR. Meanwhile, you can install it using:

opam install --ignore-constraints-on=coq-mathcomp-finmap

**Comment by strub** [comment]
Regarding `Ordef.Def`, which version of mathcomp are you using?

**Comment by amahboubi** [comment]
> @amahboubi could you confirm that you are now able to compile multinomials v1.4?

woops sorry, your message went under my radar. Yes I confirm I compiled it with coq v8.10.1. I still have to upgrade to  v8.11. But I am not using `opam` anymore.

**Comment by thery** [comment]
> Regarding `Ordef.Def`, which version of mathcomp are you using?

with
```
coq                     8.10.1      pinned to version 8.10.1
coq-mathcomp-algebra    1.10.0      Mathematical Components Library on Algebra
coq-mathcomp-bigenough  1.0.0       A small library to do epsilon - N reasonning
coq-mathcomp-field      1.10.0      Mathematical Components Library on Fields
coq-mathcomp-fingroup   1.10.0      Mathematical Components Library on finite gr
coq-mathcomp-finmap     1.4.0       Finite sets, finite maps, finitely supported
coq-mathcomp-solvable   1.10.0      Mathematical Components Library on finite gr
coq-mathcomp-ssreflect  1.10.0      Small Scale Reflection
```

```opam install --ignore-constraints-on=coq-mathcomp-finmap coq-mathcomp-multinomials```

fails with 

```# File "./src/mpoly.v", line 93, characters 7-16:
# Error: Order.Def is not a module
```

**Comment by hivert** [comment]
As far as I understand, the problem is with
```
coq-mathcomp-finmap     1.4.0
```
which reorganized the module and the name of the mixins.

**Comment by CohenCyril** [comment]
@hivert For now, to my knowledge there is no version of anything (including multinomials) compatible with finmap 1.4.

**Comment by thery** [comment]
With mathcomp 1.10, I got multinomials with opam by first getting finmap 1.3.4
```opam install --ignore-constraints-on=coq-mathcomp-ssreflect coq-mathcomp-finmap.1.3.4``` 
and then multinomials
```opam install --ignore-constraints-on=coq-mathcomp-ssreflect coq-mathcomp-multinomial```

**Comment by hivert** [comment]
@CohenCyril : there is https://github.com/hivert/FormalPowerSeries ;-)

**Comment by strub** [comment]
@amahboubi, @hivert, @thery: The library version 1.5 now works with finmap 1.4 --- but won't work with finmap 1.3.4. I don't think having both is something we want.

I also hope that I fixed all the dependency hell in the opam packages. If not, please, reopen an issue.
