### ISSUE TITLE
multinomial and coq-native

### ISSUE THREAD

**Issue by thery** [math-comp/multinomials#52]
when I try to compile my `grobner` code with `coq 8.14` and `coq-mathcomp-ssreflect   1.13.0`, `coq-native ` and `coq-mathcomp-multinomials 1.5.4` , I get an error message
```
% make
COQDEP VFILES
COQC grobner.v
COQNATIVE grobner.vo
File "./.coq-native/Nmathcomp_contrib_grobner_grobner.native", line 13, characters 5-65:
13 |     (NSsrMultinomials_mpoly.const_NSsrMultinomials_mpoly_mpoly_of
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module NSsrMultinomials_mpoly
Error: Native compiler exited with status 2
```

what should I do?

**Comment by strub** [comment]
This might be a question that @erikmd can answer.

**Comment by erikmd** [comment]
Hi, thanks @strub for the ping! and sorry for late reply, I was abroad this week.

@thery the error you get certainly comes from the fact you use the last multinomials release which does not include PRs #45, #48, #49 

To overcome this, you can use the master version of multinomials (note: it is unneeded to add extra-dev for that, see below) before multinomials 1.5.5 or so is released:

```bash
opam pin add -n -y -k git coq-mathcomp-multinomials.1.5.4 "https://github.com/math-comp/multinomials.git#master"
# the 1.5.4 above is a dummy version string: this trick allows to use master as if it were 1.5.4 (for reverse dependencies)
opam install -j 2 coq-native coq-mathcomp-multinomials
```

**Comment by erikmd** [comment]
> To overcome this, you can use the master version of multinomials (…)

But meanwhile, I've opened a PR in https://github.com/coq/opam-coq-archive/pull/1929 to ensure the incompatibility mentioned in this issue can show up much earlier in the opam compilation (I remember this idea had been suggested by @proux01)

**Comment by thery** [comment]
@erikmd thanks eric. Would be nice to have a new opam version of multinomial with the patch

**Comment by proux01** [comment]
@strub there is currently no release of multinomials compatible with coq 8.15 which should come out in the next few weeks, could we please get a release (the master branch seems to work fine with the release candidate 8.15+rc1)?

**Comment by strub** [comment]
Is releasing current master is ok to you?

**Comment by proux01** [comment]
That would be perfect.

**Comment by strub** [comment]
Done.

**Comment by proux01** [comment]
Thanks a lot! I just opened a PR on OPAM coq archive: https://github.com/coq/opam-coq-archive/pull/2027
