### ISSUE TITLE
Failure with coq master

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/multinomials#64]
This `apply` seems to fail now with coq master.
https://github.com/math-comp/multinomials/blob/4ca918093c52fb5b00d9190b855ac42d522cc9cc/src/mpoly.v#L4437

**Comment by CohenCyril** [comment]
fixed by #63

**Comment by strub** [comment]
Hi @CohenCyril. See my comment in #63. I am a bit lost here.

**Comment by pi8027** [comment]
CI supports the fact that the issue has disappeared at some point. So, I'm closing this issue. (Feel free to reopen.)
