### ISSUE TITLE
Releasing a multinomials 1.6.0

### ISSUE THREAD

**Issue by proux01** [math-comp/multinomials#77]
@strub we would need a release of the current master branch of multinomials:
* so that we have a version of multinomials compatible with the just released mathcomp 1.17.0
* so that we have a release incorporating the change of logpath Ssrmultinomials -> mathcomp.multinomials (that's why I'd go for a 1.6.0 rather than 1.5.7)
* it would also be a last release compatible with mathcomp 1 once we merge https://github.com/math-comp/multinomials/pull/42 after releasing mathcomp 2 (which we are finalizing today)

(I can take care of the OPAM and Nix packages once the github released is done)

**Comment by CohenCyril** [comment]
I can do it
