### ISSUE TITLE
#90 broke nix derivation

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/multinomials#91]
PR #90 broke nix derivation by switching back to dune.

**Comment by Tragicus** [comment]
Should not https://github.com/NixOS/nixpkgs/pull/327568 have restored it, though?

**Comment by CohenCyril** [comment]
Ah should have...

**Comment by pi8027** [comment]
Hi, what is the status of this issue?

**Comment by pi8027** [comment]
I'm closing this issue, but feel free to reopen it if it is actually not fixed.
